name: live_exchange_rate_converter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  currency_text_input_formatter: ^2.2.3
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  intl: ^0.19.0
  session_storage: ^0.0.1
  universal_html: ^2.2.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/empty.png
    - assets/images/background.png
    - assets/images/currency-icons/
    - assets/images/currency-icons/aed.png
    - assets/images/currency-icons/fok.png
    - assets/images/currency-icons/ggp.png
    - assets/images/currency-icons/imp.png
    - assets/images/currency-icons/jep.png
    - assets/images/currency-icons/kid.png
    - assets/images/currency-icons/lsl.png
    - assets/images/currency-icons/mru.png
    - assets/images/currency-icons/pab.png
    - assets/images/currency-icons/sdg.png
    - assets/images/currency-icons/sle.png
    - assets/images/currency-icons/ssp.png
    - assets/images/currency-icons/stn.png
    - assets/images/currency-icons/tmt.png
    - assets/images/currency-icons/tvd.png
    - assets/images/currency-icons/ves.png
    - assets/images/currency-icons/xdr.png
    - assets/images/currency-icons/zwl.png
    - assets/images/currency-icons/bdt.png
    - assets/images/currency-icons/bzd.png
    - assets/images/currency-icons/dkk.png
    - assets/images/currency-icons/gip.png
    - assets/images/currency-icons/inr.png
    - assets/images/currency-icons/krw.png
    - assets/images/currency-icons/mga.png
    - assets/images/currency-icons/nad.png
    - assets/images/currency-icons/pyg.png
    - assets/images/currency-icons/sll.png
    - assets/images/currency-icons/ttd.png
    - assets/images/currency-icons/xaf.png
    - assets/images/currency-icons/afn.png
    - assets/images/currency-icons/bgn.png
    - assets/images/currency-icons/cad.png
    - assets/images/currency-icons/dop.png
    - assets/images/currency-icons/gmd.png
    - assets/images/currency-icons/iqd.png
    - assets/images/currency-icons/kwd.png
    - assets/images/currency-icons/mkd.png
    - assets/images/currency-icons/ngn.png
    - assets/images/currency-icons/qar.png
    - assets/images/currency-icons/sos.png
    - assets/images/currency-icons/twd.png
    - assets/images/currency-icons/xcd.png
    - assets/images/currency-icons/all.png
    - assets/images/currency-icons/bhd.png
    - assets/images/currency-icons/cdf.png
    - assets/images/currency-icons/dzd.png
    - assets/images/currency-icons/gnf.png
    - assets/images/currency-icons/irr.png
    - assets/images/currency-icons/kyd.png
    - assets/images/currency-icons/mmk.png
    - assets/images/currency-icons/nio.png
    - assets/images/currency-icons/ron.png
    - assets/images/currency-icons/srd.png
    - assets/images/currency-icons/tzs.png
    - assets/images/currency-icons/xof.png
    - assets/images/currency-icons/amd.png
    - assets/images/currency-icons/bif.png
    - assets/images/currency-icons/chf.png
    - assets/images/currency-icons/egp.png
    - assets/images/currency-icons/gtq.png
    - assets/images/currency-icons/isk.png
    - assets/images/currency-icons/kzt.png
    - assets/images/currency-icons/mnt.png
    - assets/images/currency-icons/nok.png
    - assets/images/currency-icons/rsd.png
    - assets/images/currency-icons/std.png
    - assets/images/currency-icons/uah.png
    - assets/images/currency-icons/xpf.png
    - assets/images/currency-icons/ang.png
    - assets/images/currency-icons/bmd.png
    - assets/images/currency-icons/clp.png
    - assets/images/currency-icons/ern.png
    - assets/images/currency-icons/gyd.png
    - assets/images/currency-icons/jmd.png
    - assets/images/currency-icons/lak.png
    - assets/images/currency-icons/mop.png
    - assets/images/currency-icons/npr.png
    - assets/images/currency-icons/rub.png
    - assets/images/currency-icons/svc.png
    - assets/images/currency-icons/ugx.png
    - assets/images/currency-icons/yer.png
    - assets/images/currency-icons/aoa.png
    - assets/images/currency-icons/bnd.png
    - assets/images/currency-icons/cny.png
    - assets/images/currency-icons/etb.png
    - assets/images/currency-icons/hkd.png
    - assets/images/currency-icons/jod.png
    - assets/images/currency-icons/lbp.png
    - assets/images/currency-icons/mro.png
    - assets/images/currency-icons/nzd.png
    - assets/images/currency-icons/rwf.png
    - assets/images/currency-icons/syp.png
    - assets/images/currency-icons/usd.png
    - assets/images/currency-icons/zar.png
    - assets/images/currency-icons/ars.png
    - assets/images/currency-icons/bob.png
    - assets/images/currency-icons/cop.png
    - assets/images/currency-icons/eur.png
    - assets/images/currency-icons/hnl.png
    - assets/images/currency-icons/jpy.png
    - assets/images/currency-icons/lkr.png
    - assets/images/currency-icons/mur.png
    - assets/images/currency-icons/omr.png
    - assets/images/currency-icons/sar.png
    - assets/images/currency-icons/szl.png
    - assets/images/currency-icons/uyu.png
    - assets/images/currency-icons/zmw.png
    - assets/images/currency-icons/aud.png
    - assets/images/currency-icons/brl.png
    - assets/images/currency-icons/crc.png
    - assets/images/currency-icons/fjd.png
    - assets/images/currency-icons/hrk.png
    - assets/images/currency-icons/kes.png
    - assets/images/currency-icons/lrd.png
    - assets/images/currency-icons/mvr.png
    - assets/images/currency-icons/pen.png
    - assets/images/currency-icons/sbd.png
    - assets/images/currency-icons/thb.png
    - assets/images/currency-icons/uzs.png
    - assets/images/currency-icons/awg.png
    - assets/images/currency-icons/bsd.png
    - assets/images/currency-icons/cup.png
    - assets/images/currency-icons/fkp.png
    - assets/images/currency-icons/htg.png
    - assets/images/currency-icons/kgs.png
    - assets/images/currency-icons/ltl.png
    - assets/images/currency-icons/mwk.png
    - assets/images/currency-icons/pgk.png
    - assets/images/currency-icons/scr.png
    - assets/images/currency-icons/tjs.png
    - assets/images/currency-icons/vef.png
    - assets/images/currency-icons/azn.png
    - assets/images/currency-icons/btn.png
    - assets/images/currency-icons/cve.png
    - assets/images/currency-icons/gbp.png
    - assets/images/currency-icons/huf.png
    - assets/images/currency-icons/khr.png
    - assets/images/currency-icons/lyd.png
    - assets/images/currency-icons/mxn.png
    - assets/images/currency-icons/php.png
    - assets/images/currency-icons/sek.png
    - assets/images/currency-icons/tnd.png
    - assets/images/currency-icons/vnd.png
    - assets/images/currency-icons/bam.png
    - assets/images/currency-icons/bwp.png
    - assets/images/currency-icons/czk.png
    - assets/images/currency-icons/gel.png
    - assets/images/currency-icons/idr.png
    - assets/images/currency-icons/kmf.png
    - assets/images/currency-icons/mad.png
    - assets/images/currency-icons/myr.png
    - assets/images/currency-icons/pkr.png
    - assets/images/currency-icons/sgd.png
    - assets/images/currency-icons/top.png
    - assets/images/currency-icons/vuv.png
    - assets/images/currency-icons/bbd.png
    - assets/images/currency-icons/byn.png
    - assets/images/currency-icons/djf.png
    - assets/images/currency-icons/ghs.png
    - assets/images/currency-icons/ils.png
    - assets/images/currency-icons/kpw.png
    - assets/images/currency-icons/mdl.png
    - assets/images/currency-icons/mzn.png
    - assets/images/currency-icons/pln.png
    - assets/images/currency-icons/shp.png
    - assets/images/currency-icons/try.png
    - assets/images/currency-icons/wst.png
    - assets/images/currency-icons/npr.png
    - assets/images/currency-icons/sar.png
    - assets/images/currency-icons/sgd.png
    - assets/images/currency-icons/xaf.png
    - assets/images/currency-icons/xof.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Overpass
      fonts:
        - asset: fonts/Overpass/Overpass-Black.ttf
          weight: 900
        - asset: fonts/Overpass/Overpass-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Overpass/Overpass-ExtraBold.ttf
          weight: 800
        - asset: fonts/Overpass/Overpass-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Overpass/Overpass-Bold.ttf
          weight: 700
        - asset: fonts/Overpass/Overpass-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/Overpass/Overpass-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Overpass/Overpass-Medium.ttf
          weight: 500
        - asset: fonts/Overpass/Overpass-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/Overpass/Overpass-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLight.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Overpass/Overpass-Thin.ttf
          weight: 100
        - asset: fonts/Overpass/Overpass-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
