name: live_exchange_rate_converter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  currency_text_input_formatter: ^2.2.3
  flutter:
    sdk: flutter

  flutter_dotenv: ^6.0.0
  http: ^1.2.1
  intl: ^0.19.0
  session_storage: ^0.0.1
  universal_html: ^2.2.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/empty.png
    - assets/images/background.png
    - assets/images/aed.png
    - assets/images/fok.png
    - assets/images/ggp.png
    - assets/images/imp.png
    - assets/images/jep.png
    - assets/images/kid.png
    - assets/images/lsl.png
    - assets/images/mru.png
    - assets/images/pab.png
    - assets/images/sdg.png
    - assets/images/sle.png
    - assets/images/ssp.png
    - assets/images/stn.png
    - assets/images/tmt.png
    - assets/images/tvd.png
    - assets/images/ves.png
    - assets/images/xdr.png
    - assets/images/zwl.png
    - assets/images/bdt.png
    - assets/images/bzd.png
    - assets/images/dkk.png
    - assets/images/gip.png
    - assets/images/inr.png
    - assets/images/krw.png
    - assets/images/mga.png
    - assets/images/nad.png
    - assets/images/pyg.png
    - assets/images/sll.png
    - assets/images/ttd.png
    - assets/images/xaf.png
    - assets/images/afn.png
    - assets/images/bgn.png
    - assets/images/cad.png
    - assets/images/dop.png
    - assets/images/gmd.png
    - assets/images/iqd.png
    - assets/images/kwd.png
    - assets/images/mkd.png
    - assets/images/ngn.png
    - assets/images/qar.png
    - assets/images/sos.png
    - assets/images/twd.png
    - assets/images/xcd.png
    - assets/images/all.png
    - assets/images/bhd.png
    - assets/images/cdf.png
    - assets/images/dzd.png
    - assets/images/gnf.png
    - assets/images/irr.png
    - assets/images/kyd.png
    - assets/images/mmk.png
    - assets/images/nio.png
    - assets/images/ron.png
    - assets/images/srd.png
    - assets/images/tzs.png
    - assets/images/xof.png
    - assets/images/amd.png
    - assets/images/bif.png
    - assets/images/chf.png
    - assets/images/egp.png
    - assets/images/gtq.png
    - assets/images/isk.png
    - assets/images/kzt.png
    - assets/images/mnt.png
    - assets/images/nok.png
    - assets/images/rsd.png
    - assets/images/std.png
    - assets/images/uah.png
    - assets/images/xpf.png
    - assets/images/ang.png
    - assets/images/bmd.png
    - assets/images/clp.png
    - assets/images/ern.png
    - assets/images/gyd.png
    - assets/images/jmd.png
    - assets/images/lak.png
    - assets/images/mop.png
    - assets/images/npr.png
    - assets/images/rub.png
    - assets/images/svc.png
    - assets/images/ugx.png
    - assets/images/yer.png
    - assets/images/aoa.png
    - assets/images/bnd.png
    - assets/images/cny.png
    - assets/images/etb.png
    - assets/images/hkd.png
    - assets/images/jod.png
    - assets/images/lbp.png
    - assets/images/mro.png
    - assets/images/nzd.png
    - assets/images/rwf.png
    - assets/images/syp.png
    - assets/images/usd.png
    - assets/images/zar.png
    - assets/images/ars.png
    - assets/images/bob.png
    - assets/images/cop.png
    - assets/images/eur.png
    - assets/images/hnl.png
    - assets/images/jpy.png
    - assets/images/lkr.png
    - assets/images/mur.png
    - assets/images/omr.png
    - assets/images/sar.png
    - assets/images/szl.png
    - assets/images/uyu.png
    - assets/images/zmw.png
    - assets/images/aud.png
    - assets/images/brl.png
    - assets/images/crc.png
    - assets/images/fjd.png
    - assets/images/hrk.png
    - assets/images/kes.png
    - assets/images/lrd.png
    - assets/images/mvr.png
    - assets/images/pen.png
    - assets/images/sbd.png
    - assets/images/thb.png
    - assets/images/uzs.png
    - assets/images/awg.png
    - assets/images/bsd.png
    - assets/images/cup.png
    - assets/images/fkp.png
    - assets/images/htg.png
    - assets/images/kgs.png
    - assets/images/ltl.png
    - assets/images/mwk.png
    - assets/images/pgk.png
    - assets/images/scr.png
    - assets/images/tjs.png
    - assets/images/vef.png
    - assets/images/azn.png
    - assets/images/btn.png
    - assets/images/cve.png
    - assets/images/gbp.png
    - assets/images/huf.png
    - assets/images/khr.png
    - assets/images/lyd.png
    - assets/images/mxn.png
    - assets/images/php.png
    - assets/images/sek.png
    - assets/images/tnd.png
    - assets/images/vnd.png
    - assets/images/bam.png
    - assets/images/bwp.png
    - assets/images/czk.png
    - assets/images/gel.png
    - assets/images/idr.png
    - assets/images/kmf.png
    - assets/images/mad.png
    - assets/images/myr.png
    - assets/images/pkr.png
    - assets/images/sgd.png
    - assets/images/top.png
    - assets/images/vuv.png
    - assets/images/bbd.png
    - assets/images/byn.png
    - assets/images/djf.png
    - assets/images/ghs.png
    - assets/images/ils.png
    - assets/images/kpw.png
    - assets/images/mdl.png
    - assets/images/mzn.png
    - assets/images/pln.png
    - assets/images/shp.png
    - assets/images/try.png
    - assets/images/wst.png
    - assets/images/npr.png
    - assets/images/sar.png
    - assets/images/sgd.png
    - assets/images/xaf.png
    - assets/images/xof.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Overpass
      fonts:
        - asset: fonts/Overpass/Overpass-Black.ttf
          weight: 900
        - asset: fonts/Overpass/Overpass-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Overpass/Overpass-ExtraBold.ttf
          weight: 800
        - asset: fonts/Overpass/Overpass-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Overpass/Overpass-Bold.ttf
          weight: 700
        - asset: fonts/Overpass/Overpass-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/Overpass/Overpass-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Overpass/Overpass-Medium.ttf
          weight: 500
        - asset: fonts/Overpass/Overpass-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/Overpass/Overpass-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Overpass/Overpass-Light.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLight.ttf
          weight: 300
        - asset: fonts/Overpass/Overpass-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Overpass/Overpass-Thin.ttf
          weight: 100
        - asset: fonts/Overpass/Overpass-ThinItalic.ttf
          style: italic
          weight: 100
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 300
        - asset: fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
